"""makeTables.py -- every table in the paper, written to tables/ as LaTeX.

    python makeTables.py                 all tables (about 6 minutes)
    python makeTables.py inverse         just that one
    python makeTables.py --list          names and destinations

Each file holds only the `tabular`, so the surrounding `table` environment,
the caption and the label stay in main.tex where they can be edited:

    \\begin{table}[H]
    \\caption{...}
    \\label{tab:inverse}
    \\centering
    \\input{tables/inverse}
    \\end{table}

Every claim the text makes about a table is ASSERTED before the table is
written, so a table cannot go stale relative to the code. Square inclusion,
v_f = 1/4, plane strain, nu = 0.35, contrast rho = 10.
"""
from __future__ import annotations

import os
import sys

import numpy as np

from verify_square import spectra, alpha_two_phase, prop3_check
from verify_full_unitary import full_error
from verify_inverse import inverse_case, residual, LOADS

TABDIR = "tables"
RHO = 10.0
EPS = 1e-6


def write(name: str, spec: str, header: list[str], rows: list) -> None:
    """Emit one tabular."""
    os.makedirs(TABDIR, exist_ok=True)
    out = ["% generated by makeTables.py -- do not edit",
           f"\\begin{{tabular}}{{{spec}}}", "\\toprule",
           " & ".join(header) + r"\\", "\\midrule"]
    out += [" & ".join(str(c) for c in r) + r"\\" for r in rows]
    out += ["\\bottomrule", "\\end{tabular}", ""]
    open(f"{TABDIR}/{name}.tex", "w").write("\n".join(out))
    print(f"    {TABDIR}/{name}.tex")


def sci(x: float, digits: int = 2) -> str:
    """$a.b \\times 10^{e}$ with `digits` significant digits."""
    e = int(np.floor(np.log10(abs(x))))
    m = round(x / 10 ** e, digits - 1)
    if abs(m) >= 10:
        m, e = m / 10, e + 1
    return f"${m:.{digits - 1}f} \\times 10^{{{e}}}$"


def kappa_fmt(x: float) -> str:
    return f"${x:.0f}$" if x < 1000 else sci(x, 3)


# ==========================================================================
#  Table 1 (tab:kappa): condition numbers seen by QSVT
# ==========================================================================
def tab_kappa() -> None:
    alpha = alpha_two_phase(RHO)
    rows, prev = [], None
    for N in (8, 16, 32, 64):
        r = spectra(N, RHO)
        kK = alpha / r["Kmin"]
        kM = r["kappaM"]
        assert abs(kM / RHO - 1) < 1e-9, (N, kM)                    # "equals rho at every N"
        if prev is not None:
            assert 3.5 < kK / prev < 4.0, (N, kK / prev)            # "approaching 4 per doubling"
        prev = kK
        rows.append([f"${N}$", kappa_fmt(kK), f"${kM:.3f}$"])
    write("kappa", "rrr", ["$N$", "$\\kappa(\\Kchi)$", "$\\kappa(\\tilde{\\mat{M}})$"], rows)
    print(f"       alpha = {alpha:.2f} (text: 9.97)")


# ==========================================================================
#  Table 2 (tab:be-M): encoding of Mtilde from the gate-level circuit
# ==========================================================================
def tab_be_M() -> None:
    rows = []
    for N in (8, 16):
        for F in (24, 32):
            r = prop3_check(N, RHO, F)
            _, delta, chk = full_error(int(np.log2(N)), F)
            assert r["clean"] and chk["work_bits_left_set"] == 0
            assert r["err"] < 2 * delta, (N, F, r["err"], delta)    # "below 2 delta"
            assert abs(r["spec_min"] * RHO - 1) < 1e-12 and abs(r["spec_max"] - 1) < 1e-12
            assert abs(r["cbar"] - 0.325) < 1e-12
            rows.append([f"${N}$", f"${F}$", sci(r["err"]), sci(2 * delta)])
    write("be_M", "rrrr", ["$N$", "$F$", "difference", "$2\\delta$"], rows)


# ==========================================================================
#  Table 3 (tab:inverse): the preconditioned inverse on four loads
# ==========================================================================
def tab_inverse() -> None:
    res = residual(RHO, EPS)
    rows, dev = [], {24: 0.0, 32: 0.0}
    for N in (8, 16, 32, 64):
        r = inverse_case(N, RHO, EPS, F_bits=(24, 32) if N <= 16 else ())
        e = r["errs"]
        assert max(e.values()) <= EPS, (N, e)                       # "at most eps_p"
        assert abs(e["worst"] / res - 1) < 1e-3, (N, e["worst"], res)   # "equals the residual"
        for Fb, ec in r["circuit"].items():
            dev[Fb] = max(dev[Fb], max(abs(ec[k] - e[k]) for k in LOADS))
        rows.append([f"${N}$", f"${r['d']}$", f"${r['pcg']}$"] + [sci(e[k]) for k in LOADS])
    assert dev[32] < 1e-8 and dev[24] < 2.2e-7, dev                 # "two digits", "at most 2.2e-7"
    write("inverse", "rrrrrrr",
          ["$N$", "$d$", "PCG", "smooth", "random", "cell", "worst"], rows)
    print(f"       residual of q_t = {res:.3e}; circuit deviation F=24: {dev[24]:.1e}, "
          f"F=32: {dev[32]:.1e}")


TABLES = {
    "kappa":   (tab_kappa,   "Table 1, condition numbers (tab:kappa)"),
    "be_M":    (tab_be_M,    "Table 2, encoding of Mtilde (tab:be-M)"),
    "inverse": (tab_inverse, "Table 3, the inverse on four loads (tab:inverse)"),
}


def main(argv) -> None:
    if "--list" in argv:
        for k, (_, d) in TABLES.items():
            print(f"  {k:<8} {d}")
        return
    wanted = [a for a in argv if not a.startswith("-")] or list(TABLES)
    bad = [w for w in wanted if w not in TABLES]
    if bad:
        raise SystemExit(f"unknown table(s) {bad}; choose from {sorted(TABLES)}")
    for name in wanted:
        fn, desc = TABLES[name]
        print(f"{name}  ({desc})")
        fn()
    print("\ndone")


if __name__ == "__main__":
    main(sys.argv[1:])
